#!/usr/bin/env python3
"""Fetch film.recipes signature recipe posts and generate Dart source data."""
import html
import os
import re
import sys
import time
import urllib.request

UA = {'User-Agent': 'Mozilla/5.0 (phos-app data generation)'}

# The "Recipes I'm Known For" signature list. Re-resolve the URLs from the
# index page when the list changes:
#   https://film.recipes/blog/most-popular-film-recipes/
INDEX = 'https://film.recipes/blog/most-popular-film-recipes/'
OUT = 'app/lib/data/film_recipes_data.dart'


def get(url):
    req = urllib.request.Request(url, headers=UA)
    with urllib.request.urlopen(req, timeout=30) as r:
        return r.read().decode('utf-8', 'replace')


def meta(h, prop):
    m = re.search(r'<meta[^>]+property="%s"[^>]+content="([^"]*)"' % re.escape(prop), h)
    if not m:
        m = re.search(r'<meta[^>]+content="([^"]*)"[^>]+property="%s"' % re.escape(prop), h)
    return html.unescape(m.group(1)) if m else None


def title(h):
    t = meta(h, 'og:title')
    if t:
        return html.unescape(t)
    m = re.search(r'<h1[^>]*>(.*?)</h1>', h, re.S)
    return html.unescape(re.sub(r'<[^>]+>', '', m.group(1))).strip() if m else None


def settings(h):
    i = h.find('class="recipe-settings"')
    if i < 0:
        return None
    start = h.rfind('<table', 0, i)
    end = h.find('</table>', i)
    block = h[start:end]
    rows = re.findall(r'<tr>\s*<td[^>]*>(.*?)</td>\s*<td[^>]*>(.*?)</td>\s*</tr>', block, re.S)
    out = []
    for k, v in rows:
        k = html.unescape(re.sub(r'<[^>]+>', '', k)).strip()
        v = html.unescape(re.sub(r'<[^>]+>', '', v)).strip()
        v = v.replace('\u2011', '-').replace('\u2212', '-').replace('\u2013', '-')
        out.append(f'{k}: {v}')
    return out


def recipe_name(t):
    if not t:
        return None
    for sep in (' \u2013 ', ' \u2014 ', ' - ', '. ', ', ', ' for ', ' with '):
        if sep in t:
            t = t.split(sep)[0]
            break
    t = t.strip()
    m = re.search(r'\bFilm Recipe\b', t, flags=re.I)
    if m:
        t = t[: m.start()].strip()
    t = re.sub(r'\s+Film Recipe$', '', t, flags=re.I)
    return t or None


def clean_desc(desc, name, title):
    if not desc:
        return None
    d = desc.strip()
    for pre in (name, title):
        if pre and d.startswith(pre):
            d = d[len(pre):].lstrip(' \u2013\u2014-')
    d = d.strip()
    if len(d) < 40:
        return None
    if len(d) > 140:
        d = d[:140].rsplit(' ', 1)[0] + '\u2026'
    return d


def dart_str(s):
    return "'" + s.replace('\\', '\\\\').replace("'", '\\\'') + "'"


def index_urls():
    h = get(INDEX)
    links = re.findall(r'href="(https://film\.recipes/\d{4}/\d{2}/\d{2}/[a-z0-9\-]+/)"', h)
    seen = []
    for l in links:
        if l not in seen:
            seen.append(l)
    return seen


def main():
    entries = []
    errors = []
    for url in index_urls():
        try:
            h = get(url)
            st = settings(h)
            if not st or len(st) < 4:
                errors.append((url, f'settings rows: {len(st) if st else 0}'))
                continue
            t = title(h)
            name = recipe_name(t) or t or url.rsplit('/', 2)[-2]
            desc = clean_desc(meta(h, 'og:description'), name, t)
            slug = url.rstrip('/').rsplit('/', 1)[-1]
            entries.append({'url': url, 'name': name, 'desc': desc, 'settings': st, 'slug': slug})
            print(f'ok  {name!r} ({len(st)} fields)')
        except Exception as e:
            errors.append((url, str(e)))
            print(f'ERR {url}: {e}', file=sys.stderr)
        time.sleep(0.4)

    print(f'\n{len(entries)} entries, {len(errors)} errors')
    for u, e in errors:
        print(f'  FAIL {u}: {e}', file=sys.stderr)

    lines = []
    lines.append('// Generated by tool/fetch_film_recipes.py — do not edit by hand.')
    lines.append('//')
    lines.append('// The "Recipes I\'m Known For" signature looks from film.recipes,')
    lines.append('// https://film.recipes/blog/most-popular-film-recipes/ (Justin Gould).')
    lines.append('// Settings text is the verbatim label/value table from each post;')
    lines.append('// every entry keeps a link to its original page for attribution.')
    lines.append('//')
    lines.append('class FilmRecipeSource {')
    lines.append('  const FilmRecipeSource({')
    lines.append('    required this.id,')
    lines.append('    required this.name,')
    lines.append('    required this.sourceUrl,')
    lines.append('    required this.settings,')
    lines.append('    this.description,')
    lines.append('  });')
    lines.append('')
    lines.append('  final String id;')
    lines.append('  final String name;')
    lines.append('  final String sourceUrl;')
    lines.append('  final String? description;')
    lines.append('')
    lines.append("  /// Verbatim settings in the shared Fuji text layout")
    lines.append('  /// (`Label: Value` per line) understood by FujiRecipeParser.')
    lines.append('  final String settings;')
    lines.append('}')
    lines.append('')
    lines.append('const List<FilmRecipeSource> filmRecipeSources = [')
    for e in entries:
        lines.append('  FilmRecipeSource(')
        lines.append(f'    id: {dart_str(e["slug"])},')
        lines.append(f'    name: {dart_str(e["name"])},')
        lines.append(f'    sourceUrl: {dart_str(e["url"])},')
        if e['desc']:
            lines.append(f'    description: {dart_str(e["desc"])},')
        lines.append('    settings: \'\'\'')
        lines.extend(e['settings'])
        lines.append('\'\'\',')
        lines.append('  ),')
    lines.append('];')
    out = OUT if os.path.isabs(OUT) else os.path.join(
        os.path.dirname(os.path.dirname(os.path.abspath(__file__))), OUT)
    os.makedirs(os.path.dirname(out), exist_ok=True)
    open(out, 'w').write('\n'.join(lines) + '\n')
    print(f'wrote {out}')


if __name__ == '__main__':
    main()