// Generated by tool/fetch_film_recipes.py — do not edit by hand.
//
// The "Recipes I'm Known For" signature looks from film.recipes,
// https://film.recipes/blog/most-popular-film-recipes/ (Justin Gould).
// Settings text is the verbatim label/value table from each post;
// every entry keeps a link to its original page for attribution.
//
class FilmRecipeSource {
  const FilmRecipeSource({
    required this.id,
    required this.name,
    required this.sourceUrl,
    required this.settings,
    this.description,
  });

  final String id;
  final String name;
  final String sourceUrl;
  final String? description;

  /// Verbatim settings in the shared Fuji text layout
  /// (`Label: Value` per line) understood by FujiRecipeParser.
  final String settings;
}

const List<FilmRecipeSource> filmRecipeSources = [
  FilmRecipeSource(
    id: 'absolute-portra-my-best-kodak-portra-film-recipe',
    name: 'Absolute Portra',
    sourceUrl: 'https://film.recipes/2025/08/19/absolute-portra-my-best-kodak-portra-film-recipe/',
    description: 'Get the Kodak Portra 400 look on your Fujifilm X100VI with this Kodak Film Simulation Recipe The appeal of Kodak Portra 400 …',
    settings: '''
Film Simulation: Classic Chrome
Grain Effect: Weak, Small
Col. Chr. Effect: Weak
Col. Chr. Blue: Weak
White Balance: Daylight, +2 Red, -5 Blue
Dynamic Range: DR400
Highlights: -1
Shadows: -1
Colour: 0
Sharpness: -2
ISO N.R.: -4
Clarity: -2
EV Comp.: +1/3
''',
  ),
  FilmRecipeSource(
    id: 'real-leica-film-recipe',
    name: 'Real Leica',
    sourceUrl: 'https://film.recipes/2026/02/15/real-leica-film-recipe/',
    description: 'Capturing premium colour tones with Fujifilm Reala Ace Simulation Leica cameras are a top tier product offering excellent image quality,…',
    settings: '''
Film Simulation: Reala Ace
Grain Effect: Off
Col. Chr. Effect: Strong
Col. Chr. Blue: Weak
White Balance: Auto, +2 Red, -1 Blue
Dynamic Range: DR200
Highlights: -1
Shadows: 0
Colour: 3
Sharpness: 0
ISO N.R.: -4
Clarity: 0
EV Comp.: +1/3
''',
  ),
  FilmRecipeSource(
    id: 'umbrella-film-recipe-is-this-my-best-ever-film-recipe',
    name: 'Umbrella',
    sourceUrl: 'https://film.recipes/2025/03/23/umbrella-film-recipe-is-this-my-best-ever-film-recipe/',
    description: 'Film like Classic Negative recipe, designed for rainy days but excellent in all conditions. Throughout the winter the weather was du…',
    settings: '''
Film Simulation: Classic Negative
Grain Effect: Weak, Large
Col. Chr. Effect: Weak
Col. Chr. Blue: Weak
White Balance: Auto, +1 Red, -8 Blue
Dynamic Range: DR400
Highlights: -1
Shadows: 1
Colour: -3
Sharpness: 0
ISO N.R.: -4
Clarity: -3
EV Comp.: 0
''',
  ),
  FilmRecipeSource(
    id: 'kodachrome-classic-for-70s-kodak-style',
    name: 'Kodachrome Classic',
    sourceUrl: 'https://film.recipes/2022/05/06/kodachrome-classic-for-70s-kodak-style/',
    description: 'Vintage Kodachrome film recipe for Fujifilm X-Trans IV cameras The classic Kodachrome films are much loved, and with adjustments to the Cla…',
    settings: '''
Film Simulation: Classic Chrome
Grain Effect: Off
Col. Chr. Effect: Weak
Col. Chr. Blue: Weak
White Balance: Auto, +2 Red, -3 Blue
Dynamic Range: DR200
Highlights: -1
Shadows: 0
Colour: 2
Sharpness: 1
ISO N.R.: -4
Clarity: 1
EV Comp.: 0
''',
  ),
  FilmRecipeSource(
    id: 'kojak-gold-who-loves-ya-baby',
    name: 'Kojak Gold',
    sourceUrl: 'https://film.recipes/2023/05/15/kojak-gold-who-loves-ya-baby/',
    description: 'Nostalgic classic negative film simulation recipe, like Kodak Gold prints Kojak Gold. It’s a cool name, right? It’s an even cooler look!…',
    settings: '''
Film Simulation: Classic Negative
Grain Effect: Weak, Small
Col. Chr. Effect: Off
Col. Chr. Blue: Off
White Balance: Auto, +3 Red, -6 Blue
Dynamic Range: DR400
Highlights: -0.5
Shadows: -1.5
Colour: 1
Sharpness: -1
ISO N.R.: -4
Clarity: -2
EV Comp.: 0
''',
  ),
  FilmRecipeSource(
    id: 'daido-moriyama-film-recipe',
    name: 'Daido Moriyama',
    sourceUrl: 'https://film.recipes/2023/06/15/daido-moriyama-film-recipe/',
    description: 'Monochrome film recipe based on the work of Daido Moriyama I’ve been exploring the work of some black and white photographers, looking for…',
    settings: '''
Film Simulation: Monochrome
Grain Effect: Strong, Large
White Balance: Underwater, 0 Red, 0 Blue
Dynamic Range: DR400
Highlights: -2
Shadows: 4
Sharpness: -2
ISO N.R.: -4
Clarity: 4
EV Comp.: +2/3
Mono Colour: WC +1, MG +1
''',
  ),
  FilmRecipeSource(
    id: 'back-in-the-day-like-nostalgic-film-photos',
    name: 'Back in the Day',
    sourceUrl: 'https://film.recipes/2022/07/24/back-in-the-day-like-nostalgic-film-photos/',
    description: 'Fujifilm simulation recipe for Classic Negative on X-Trans IV cameras One of the most interesting film simulations on Fuji X-series camer…',
    settings: '''
Film Simulation: Classic Negative
Grain Effect: Off
Col. Chr. Effect: Off
Col. Chr. Blue: Off
White Balance: 5600K, +4 Red, -5 Blue
Dynamic Range: DR200
Highlights: 1.5
Shadows: -1.5
Colour: 2
Sharpness: -2
ISO N.R.: -4
Clarity: 0
EV Comp.: 0
''',
  ),
  FilmRecipeSource(
    id: 'astia-pops-punchy-colour-film-recipe',
    name: 'Astia Pops',
    sourceUrl: 'https://film.recipes/2023/11/09/astia-pops-punchy-colour-film-recipe/',
    description: 'Vivid natural colour film recipe using Astia simulation for rich color Many Fujifilm film recipes have a soft tones or nostalgic look, but…',
    settings: '''
Film Simulation: Astia/Soft
Grain Effect: Off
Col. Chr. Effect: Weak
Col. Chr. Blue: Off
White Balance: Auto, 0 Red, -4 Blue
Dynamic Range: DR400
Highlights: -1
Shadows: -2
Colour: 4
Sharpness: 1
ISO N.R.: -4
Clarity: 2
EV Comp.: 0
''',
  ),
  FilmRecipeSource(
    id: 'kodak-portra-grainy-for-a-portra-400-look',
    name: 'Kodak Portra Grainy',
    sourceUrl: 'https://film.recipes/2022/05/15/kodak-portra-grainy-for-a-portra-400-look/',
    description: 'Fujifilm X-Trans 4 film recipe for a Kodak Portra 400 style Kodak Portra film was hugely popular, and with its different versions, came…',
    settings: '''
Film Simulation: Classic Negative
Grain Effect: Strong, Large
Col. Chr. Effect: Strong
Col. Chr. Blue: Off
White Balance: 5200K, +2 Red, -5 Blue
Dynamic Range: DR200
Highlights: -2
Shadows: 0
Colour: 1
Sharpness: -3
ISO N.R.: -4
Clarity: -1
EV Comp.: +2/3
''',
  ),
  FilmRecipeSource(
    id: 'cineplus-a-punchy-classic-chrome-style',
    name: 'Cineplus',
    sourceUrl: 'https://film.recipes/2023/02/02/cineplus-a-punchy-classic-chrome-style/',
    description: 'Cinematic classic chrome film recipe with rich color and contrast Sometimes, when developing film recipes, the inspiration comes in the…',
    settings: '''
Film Simulation: Classic Chrome
Grain Effect: Off
Col. Chr. Effect: Strong
Col. Chr. Blue: Weak
White Balance: 5800K, +1 Red, +2 Blue
Dynamic Range: DR400
Highlights: -1
Shadows: 1
Colour: 4
Sharpness: -2
ISO N.R.: -4
Clarity: 0
EV Comp.: +2/3
''',
  ),
  FilmRecipeSource(
    id: 'astia-geographic-for-landscape-nature',
    name: 'Astia Geographic',
    sourceUrl: 'https://film.recipes/2022/07/04/astia-geographic-for-landscape-nature/',
    description: 'Fujifilm film recipe based upon Astia film simulation for natural colour It seems that the original Fujifilm film simulations, includin…',
    settings: '''
Film Simulation: Astia/Soft
Grain Effect: Off
Col. Chr. Effect: Weak
Col. Chr. Blue: Strong
White Balance: Daylight, +2 Red, -2 Blue
Dynamic Range: DR100
Highlights: 1.5
Shadows: -1.5
Colour: -2
Sharpness: 0
ISO N.R.: -4
Clarity: 2
EV Comp.: 0
''',
  ),
  FilmRecipeSource(
    id: 'kodak-portra-sw19-for-soft-wimbledon-tones',
    name: 'Kodak Portra Daily',
    sourceUrl: 'https://film.recipes/2022/07/07/kodak-portra-sw19-for-soft-wimbledon-tones/',
    description: 'Classic Chrome film silmulation recipe with Kodak Portra style tones I originally devised this Kodak Portra style film recipe to give a…',
    settings: '''
Film Simulation: Classic Chrome
Grain Effect: Weak, Small
Col. Chr. Effect: Weak
Col. Chr. Blue: Off
White Balance: Auto, +1 Red, -5 Blue
Dynamic Range: DR200
Highlights: 0.5
Shadows: -1.5
Colour: 1
Sharpness: 1
ISO N.R.: -4
Clarity: 0
EV Comp.: +1/3
''',
  ),
  FilmRecipeSource(
    id: 'agfa-apx-400-grainy-mono-film-recipe',
    name: 'Agfa APX 400',
    sourceUrl: 'https://film.recipes/2024/01/14/agfa-apx-400-grainy-mono-film-recipe/',
    description: 'A grainy black and white film recipe, based upon Agfa APX 400 film Exciting news for recipe fans … this is film recipe 250 to be added to…',
    settings: '''
Film Simulation: Acros Red Filter
Grain Effect: Strong, Large
White Balance: Fluorescent 2, 0 Red, 0 Blue
Dynamic Range: DR400
Highlights: 2
Shadows: 2
Sharpness: -2
ISO N.R.: -4
Clarity: 0
EV Comp.: 0
Mono Colour: WC -1, MG +0
''',
  ),
  FilmRecipeSource(
    id: 'goldeneye-with-extra-warm-tones',
    name: 'Goldeneye',
    sourceUrl: 'https://film.recipes/2022/08/04/goldeneye-with-extra-warm-tones/',
    description: 'Classic Negative film simulation recipe with a strong warm colour shift Here’s a recipe to deliver happy vibes in the sunshine, and bring…',
    settings: '''
Film Simulation: Classic Negative
Grain Effect: Strong, Small
Col. Chr. Effect: Weak
Col. Chr. Blue: Off
White Balance: Shade, +6 Red, -5 Blue
Dynamic Range: DR400
Highlights: -2
Shadows: 0
Colour: 1
Sharpness: -1
ISO N.R.: -4
Clarity: -1
EV Comp.: 0
''',
  ),
  FilmRecipeSource(
    id: 'classic-gold-like-expired-film-kodak-gold',
    name: 'Classic Gold',
    sourceUrl: 'https://film.recipes/2022/07/01/classic-gold-like-expired-film-kodak-gold/',
    description: 'Film simulation for old Kodak Gold 35mm for Fujifilm X-Trans IV cameras I like to follow groups and tags for 35mm film and analog photogr…',
    settings: '''
Film Simulation: Classic Negative
Grain Effect: Weak, Small
Col. Chr. Effect: Weak
Col. Chr. Blue: Off
White Balance: Auto, +6 Red, -6 Blue
Dynamic Range: DR400
Highlights: -1.5
Shadows: 0.5
Colour: -4
Sharpness: -1
ISO N.R.: -4
Clarity: 0
EV Comp.: +1/3
''',
  ),
  FilmRecipeSource(
    id: 'apple-strudel-a-delicious-autumn-recipe',
    name: 'Apple Strudel',
    sourceUrl: 'https://film.recipes/2023/09/29/apple-strudel-a-delicious-autumn-recipe/',
    description: 'Film simlulation recipe using classic negative for cream, green and orange tones. In my work on film simulation recipes, I sometimes find…',
    settings: '''
Film Simulation: Classic Negative
Grain Effect: Weak, Large
Col. Chr. Effect: Weak
Col. Chr. Blue: Off
White Balance: Fluorescent 1, +1 Red, -4 Blue
Dynamic Range: DR200
Highlights: -1
Shadows: -1
Colour: -2
Sharpness: -2
ISO N.R.: -4
Clarity: -2
EV Comp.: 0
''',
  ),
  FilmRecipeSource(
    id: 'kodak-gold-ii-classic-kodak-film-recipe',
    name: 'Kodak Gold II',
    sourceUrl: 'https://film.recipes/2026/07/19/kodak-gold-ii-classic-kodak-film-recipe/',
    description: 'An evolution of the Kodak Gold recipe — a fresh take on the classic film look with improved versatility. Kodak Gold 200 is perhaps the most…',
    settings: '''
Film Simulation: Classic Chrome
Grain Effect: Weak, Small
Col. Chr. Effect: Weak
Col. Chr. Blue: Off
White Balance: Daylight, +4 Red, -5 Blue
Dynamic Range: DR200
Highlights: -1
Shadows: 1
Colour: 1
Sharpness: -2
ISO N.R.: -4
Clarity: 0
EV Comp.: +1/3
''',
  ),
  FilmRecipeSource(
    id: 'barbour-green-deep-mood-film-recipe',
    name: 'Barbour Green',
    sourceUrl: 'https://film.recipes/2025/02/01/barbour-green-deep-mood-film-recipe/',
    description: 'Dark green film recipe with lots of mood for gloomy and bad weather days Over recent months, a lot of my focus has been directed towards…',
    settings: '''
Film Simulation: Eterna Bleach Bypass
Grain Effect: Weak, Small
Col. Chr. Effect: Weak
Col. Chr. Blue: Weak
White Balance: 5500K, -4 Red, -7 Blue
Dynamic Range: DR400
Highlights: -1
Shadows: 4
Colour: 4
Sharpness: -2
ISO N.R.: -4
Clarity: -4
EV Comp.: -2/3
''',
  ),
  FilmRecipeSource(
    id: 'superia-loco-fujifilm-low-contrast-recipe',
    name: 'Superia Loco',
    sourceUrl: 'https://film.recipes/2023/08/16/superia-loco-fujifilm-low-contrast-recipe/',
    description: 'Soft tones Fujicolor Superia look made with Classic Negative on X-Trans IV My very first film recipe creation was a Classic Negative film…',
    settings: '''
Film Simulation: Classic Negative
Grain Effect: Weak, Small
Col. Chr. Effect: Weak
Col. Chr. Blue: Off
White Balance: 4800K, +3 Red, -3 Blue
Dynamic Range: DR200
Highlights: -2
Shadows: -2
Colour: -2
Sharpness: -2
ISO N.R.: -4
Clarity: 0
EV Comp.: +1/3
''',
  ),
  FilmRecipeSource(
    id: 'waldorf-astia-new-american-color',
    name: 'Waldorf Astia',
    sourceUrl: 'https://film.recipes/2023/03/20/waldorf-astia-new-american-color/',
    description: 'Astia film simulation recipe for X Trans IV cameras to create a New American Color look Development of this Astia film simulation recipe…',
    settings: '''
Film Simulation: Astia/Soft
Grain Effect: Weak, Small
Col. Chr. Effect: Strong
Col. Chr. Blue: Off
White Balance: 6750K, -4 Red, +4 Blue
Dynamic Range: DR200
Highlights: 1
Shadows: -1
Colour: -2
Sharpness: -1
ISO N.R.: -4
Clarity: 2
EV Comp.: 0
''',
  ),
  FilmRecipeSource(
    id: 'arthouse-bleach-faded-colour-film-recipe',
    name: 'Arthouse Bleach',
    sourceUrl: 'https://film.recipes/2024/05/11/arthouse-bleach-faded-colour-film-recipe/',
    description: 'Eterna Bleach Bypass film recipe for cinematic tones and muted colour I love a muted colour look, and this draws me to shoot with film reci…',
    settings: '''
Film Simulation: Eterna Bleach Bypass
Grain Effect: Weak, Large
Col. Chr. Effect: Weak
Col. Chr. Blue: Weak
White Balance: Daylight, +2 Red, -7 Blue
Dynamic Range: DR200
Highlights: -2
Shadows: -1
Colour: 4
Sharpness: 1
ISO N.R.: -4
Clarity: 0
EV Comp.: 0
''',
  ),
  FilmRecipeSource(
    id: 'wigan-pier-sophisticated-instagram-tones',
    name: 'Wigan Pier',
    sourceUrl: 'https://film.recipes/2023/12/20/wigan-pier-sophisticated-instagram-tones/',
    description: 'Instagram inspired film simulation recipe using Eterna for warm muted images Do you follow inspiring photographers on social media, and…',
    settings: '''
Film Simulation: Eterna/Cinema
Grain Effect: Weak, Small
Col. Chr. Effect: Weak
Col. Chr. Blue: Weak
White Balance: Fluorescent 2, +2 Red, -5 Blue
Dynamic Range: DR400
Highlights: 0
Shadows: -1
Colour: -2
Sharpness: 0
ISO N.R.: -4
Clarity: 0
EV Comp.: -2/3
''',
  ),
  FilmRecipeSource(
    id: 'vinterskog-deep-tones-forest-recipe',
    name: 'Vinterskog',
    sourceUrl: 'https://film.recipes/2022/12/12/vinterskog-deep-tones-forest-recipe/',
    description: 'Bleach bypass film recipe inspired by the Swedish forest photos of Catrine Sandberg I really love misty moody photography, and would…',
    settings: '''
Film Simulation: Eterna Bleach Bypass
Grain Effect: Weak, Small
Col. Chr. Effect: Strong
Col. Chr. Blue: Weak
White Balance: 4400K, 0 Red, -4 Blue
Dynamic Range: DR400
Highlights: -2
Shadows: 2
Colour: 4
Sharpness: 0
ISO N.R.: -4
Clarity: -4
EV Comp.: +1/3
''',
  ),
  FilmRecipeSource(
    id: 'pale-barca-inspired-by-barcelona-style',
    name: 'Pale Barca',
    sourceUrl: 'https://film.recipes/2024/04/19/pale-barca-inspired-by-barcelona-style/',
    description: 'A fashion shoot film recipe using the Classic Negative film simulation Sometimes, inspiration for film recipes comes from varied sources.…',
    settings: '''
Film Simulation: Classic Negative
Grain Effect: Weak, Large
Col. Chr. Effect: Off
Col. Chr. Blue: Weak
White Balance: Auto, +2 Red, -5 Blue
Dynamic Range: DR400
Highlights: -2
Shadows: 0
Colour: -4
Sharpness: 1
ISO N.R.: -4
Clarity: -2
EV Comp.: +1/3
''',
  ),
  FilmRecipeSource(
    id: 'karmachroma-a-mellow-lo-fi-classic-chrome',
    name: 'Karmachroma',
    sourceUrl: 'https://film.recipes/2022/09/16/karmachroma-a-mellow-lo-fi-classic-chrome/',
    description: 'A nostalgic classic chrome film simulation recipe for X-Trans IV cameras Sometimes, I have a name for a recipe before I have the settings…',
    settings: '''
Film Simulation: Classic Chrome
Grain Effect: Strong, Small
Col. Chr. Effect: Weak
Col. Chr. Blue: Weak
White Balance: Auto (White Priority), +3 Red, -6 Blue
Dynamic Range: DR200
Highlights: 2
Shadows: -1
Colour: -3
Sharpness: 0
ISO N.R.: -4
Clarity: -2
EV Comp.: -1/3
''',
  ),
  FilmRecipeSource(
    id: 'dawnstar-for-a-golden-sunrise-mood',
    name: 'Dawnstar',
    sourceUrl: 'https://film.recipes/2023/01/27/dawnstar-for-a-golden-sunrise-mood/',
    description: 'Classic Negative film simulation recipe with rich colour in golden hour Here’s a warm and cosy film simulation recipe to bring extra colour…',
    settings: '''
Film Simulation: Classic Negative
Grain Effect: Weak, Small
Col. Chr. Effect: Off
Col. Chr. Blue: Off
White Balance: 6000K, +4 Red, -5 Blue
Dynamic Range: DR200
Highlights: -2
Shadows: 0
Colour: 4
Sharpness: 0
ISO N.R.: -4
Clarity: -1
EV Comp.: 0
''',
  ),
  FilmRecipeSource(
    id: 'flatpack-matte-35mm-film-recipe',
    name: 'Flatpack',
    sourceUrl: 'https://film.recipes/2023/03/05/flatpack-matte-35mm-film-recipe/',
    description: 'Fujifilm simulation film recipe for a flat tone matte look like Kodak 35mm prints This film recipe began life as an attempt to match a look…',
    settings: '''
Film Simulation: Classic Chrome
Grain Effect: Weak, Small
Col. Chr. Effect: Weak
Col. Chr. Blue: Weak
White Balance: Shade, -2 Red, -2 Blue
Dynamic Range: DR200
Highlights: -2
Shadows: -2
Colour: -2
Sharpness: -2
ISO N.R.: -4
Clarity: 0
EV Comp.: +2/3
''',
  ),
  FilmRecipeSource(
    id: 'childhood-vacation-memories-as-faded-prints',
    name: 'Childhood Vacation',
    sourceUrl: 'https://film.recipes/2023/05/19/childhood-vacation-memories-as-faded-prints/',
    description: 'Classic Negative film simulation recipe with a burned out desaturated look It’s obvious to anyone reading this site that I love…',
    settings: '''
Film Simulation: Classic Negative
Grain Effect: Strong, Large
Col. Chr. Effect: Weak
Col. Chr. Blue: Off
White Balance: Shade, +3 Red, 0 Blue
Dynamic Range: DR100
Highlights: 2
Shadows: -1
Colour: -4
Sharpness: -2
ISO N.R.: -4
Clarity: -3
EV Comp.: +1
''',
  ),
  FilmRecipeSource(
    id: 'retroscope-film-recipe-time-machine',
    name: 'Retroscope',
    sourceUrl: 'https://film.recipes/2023/11/18/retroscope-film-recipe-time-machine/',
    description: 'Bleach Bypass film simulation recipe for a nostalgic prints look Let’s wind back the decades with this nostalgic film recipe with a strong…',
    settings: '''
Film Simulation: Eterna Bleach Bypass
Grain Effect: Weak, Small
Col. Chr. Effect: Strong
Col. Chr. Blue: Weak
White Balance: 5200K, +5 Red, +2 Blue
Dynamic Range: DR200
Highlights: -1.5
Shadows: -1.5
Colour: 3
Sharpness: -3
ISO N.R.: -4
Clarity: -3
EV Comp.: 0
''',
  ),
  FilmRecipeSource(
    id: 'quicklime-limestone-classic-chrome',
    name: 'Quicklime',
    sourceUrl: 'https://film.recipes/2023/11/17/quicklime-limestone-classic-chrome/',
    description: 'Classic Chrome film simulation recipe with grey green colour balance As a fan of film recipes, I enjoy looking at photos shared by others…',
    settings: '''
Film Simulation: Classic Chrome
Grain Effect: Off
Col. Chr. Effect: Weak
Col. Chr. Blue: Off
White Balance: Shade, -2 Red, -4 Blue
Dynamic Range: DR200
Highlights: 2
Shadows: 0
Colour: -4
Sharpness: -2
ISO N.R.: -4
Clarity: -2
EV Comp.: 0
''',
  ),
  FilmRecipeSource(
    id: 'nostalgic-gold-200-bright-skies-summer-film-recipe',
    name: 'Nostalgic Gold 200',
    sourceUrl: 'https://film.recipes/2026/06/05/nostalgic-gold-200-bright-skies-summer-film-recipe/',
    description: 'A bright, cheerful Nostalgic Negative recipe with turquoise skies and a colourful character all its own. Nostalgic Gold 200 i…',
    settings: '''
Film Simulation: Nostalgic Negative
Grain Effect: Weak, Small
Col. Chr. Effect: Weak
Col. Chr. Blue: Off
White Balance: Auto (White Priority), -5 Red, -1 Blue
Dynamic Range: DR200
Highlights: 0
Shadows: 1
Colour: 4
Sharpness: 0
ISO N.R.: -4
Clarity: -3
EV Comp.: +2/3
''',
  ),
  FilmRecipeSource(
    id: 'sodium-bright-summer-recipe-with-wes-anderson-vibes',
    name: 'Sodium',
    sourceUrl: 'https://film.recipes/2026/06/05/sodium-bright-summer-recipe-with-wes-anderson-vibes/',
    description: 'A boldly yellow Classic Chrome recipe built for sunshine, summer colour and golden hour vibes. The Elements series in the Film Recipes A…',
    settings: '''
Film Simulation: Classic Chrome
Grain Effect: Weak, Small
Col. Chr. Effect: Off
Col. Chr. Blue: Off
White Balance: Fluorescent 1, +1 Red, -7 Blue
Dynamic Range: DR200
Highlights: 0
Shadows: -1
Colour: 3
Sharpness: 0
ISO N.R.: -4
Clarity: 0
EV Comp.: +1/3
''',
  ),
  FilmRecipeSource(
    id: 'old-gold-film-recipe',
    name: 'Old Gold',
    sourceUrl: 'https://film.recipes/2026/05/28/old-gold-film-recipe/',
    description: 'A mellow, brown-washed expired film look, modelled on scans of aged Kodak Gold 200. Before Fujifilm cameras, there were phone apps —…',
    settings: '''
Film Simulation: Classic Chrome
Grain Effect: Weak, Large
Col. Chr. Effect: Weak
Col. Chr. Blue: Weak
White Balance: Daylight, +4 Red, -7 Blue
Dynamic Range: DR200
Highlights: -1
Shadows: -1
Colour: -2
Sharpness: -2
ISO N.R.: -4
Clarity: -2
EV Comp.: -1/3
''',
  ),
  FilmRecipeSource(
    id: 'comic-color-film-recipe',
    name: 'Comic Color',
    sourceUrl: 'https://film.recipes/2026/05/28/comic-color-film-recipe/',
    description: 'A bold, graphic film recipe inspired by the saturated punch of pop art and comic books. Some film simulation recipes aim to be versatile…',
    settings: '''
Film Simulation: Velvia
Grain Effect: Weak, Small
Col. Chr. Effect: Weak
Col. Chr. Blue: Weak
White Balance: Fluorescent 2, -3 Red, -3 Blue
Dynamic Range: DR200
Highlights: 3
Shadows: 3
Colour: -3
Sharpness: 0
ISO N.R.: -4
Clarity: 0
EV Comp.: -1/3
''',
  ),
  FilmRecipeSource(
    id: 'bluegrass-film-recipe',
    name: 'Bluegrass',
    sourceUrl: 'https://film.recipes/2026/05/28/bluegrass-film-recipe/',
    description: 'A Classic Negative recipe that leans into blue-shifted greens for a cooler, more contemplative look. Classic Negative is a film simulation…',
    settings: '''
Film Simulation: Classic Negative
Grain Effect: Weak, Small
Col. Chr. Effect: Strong
Col. Chr. Blue: Weak
White Balance: Auto, -3 Red, 0 Blue
Dynamic Range: DR200
Highlights: 2
Shadows: -2
Colour: 2
Sharpness: -1
ISO N.R.: -4
Clarity: -2
EV Comp.: -2/3
''',
  ),
  FilmRecipeSource(
    id: 'rizzle-clicks-grainy-with-knockout-reds',
    name: 'Rizzle Clicks',
    sourceUrl: 'https://film.recipes/2026/04/27/rizzle-clicks-grainy-with-knockout-reds/',
    description: 'Rizzle Clicks, Grainy Classic Negative for Knockout Reds Grainy analog film simulation recipe with mellow greens, a warm balance and…',
    settings: '''
Film Simulation: Classic Negative
Grain Effect: Strong, Small
Col. Chr. Effect: Strong
Col. Chr. Blue: Off
White Balance: 4000K, +7 Red, -7 Blue
Dynamic Range: DR400
Highlights: -1
Shadows: -1
Colour: -1
Sharpness: 0
ISO N.R.: -4
Clarity: -2
EV Comp.: 0
''',
  ),
  FilmRecipeSource(
    id: 'controversy-film-recipe',
    name: 'Controversy',
    sourceUrl: 'https://film.recipes/2026/04/19/controversy-film-recipe/',
    description: 'is a Classic Negative film simulation recipe for Fujifilm cameras. Built for contre jour shooting, golden hour and dramatic scenes, with…',
    settings: '''
Film Simulation: Classic Negative
Grain Effect: Off
Col. Chr. Effect: Weak
Col. Chr. Blue: Weak
White Balance: Auto, +4 Red, -8 Blue
Dynamic Range: DR200
Highlights: 3
Shadows: 3
Colour: 3
Sharpness: -4
ISO N.R.: -4
Clarity: -4
EV Comp.: -1/3
''',
  ),
];
